spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: peninsula03
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
